public with sharing class Sample_S_JINController222 {

    public String getApexPageInfos() {
        return null;
    }


    public String totalClsCnt { get; set; }

    public String totalPageCnt { get; set; }

    public String debugContent { get; set; }

    public PageReference doSearch() {
        return null;
    }


    public String searchText { get; set; }

    public PageReference pageLoad() {
        return null;
    }

}